### ISSUE TITLE
[BUG] Tax cap needs to be periodically updated

### ISSUE THREAD

**Issue by YunSuk-Yeo** [terra-project/core#175]
Currently tax cap is set once at genesis and never updated during the lifecycle of the chain. This is a significant problem where the fx rates against major currencies are volatile. Moreover, the tax cap for Luna is never adjusted or even ever set, which leads the tax cap for Luna being set at 1 Luna. This could become very expensive.

**Comment by dokwon** [comment]
Especially problematic because Luna tax cap is fixed at 1 Luna (swap rates did not exist at genesis). This will make luna transfers very expensive over time. 

I propose the following: 

- Remove tax for `uluna` sends and only retain them for stablecoin transfers
- Adjust tax cap every treasury policy adjustment for stablecoins (4 weeks) - cap should still be 1 SDT
