### ISSUE TITLE
Update OpenAPI Specification for LCD

### ISSUE THREAD

**Issue by ouiliame** [terra-project/core#339]
Current Swagger specification is out-of-date. Will go over faulty endpoint definitions and try to add autogeneration.

**Comment by dokwon** [comment]
@ouiliame can you get to this?

**Comment by ouiliame** [comment]
@kjessec lol

**Comment by hanjukim** [comment]
swagger file is a dependent to AWS API Gateway now. @etienne-napoleone Is OpenAPI compatible with API Gateway?

**Comment by kjessec** [comment]
@hanjukim AFAIK FCD endpoints are auto-generated from apidoc in code and converted to swagger for API Gateway configuration. The troubling part is the LCD ones (i.e. merged from swagger file in core). While it is still compatible with API Gateway because the swagger doc itself is valid, the response models are wrong. Will need to go over every endpoint and check...

@ouiliame will attempt at fixing them later this week

**Comment by etienne-napoleone** [comment]
I believe fcd code that generates the api gateway swagger file with api gateway specific extensions does it after merging definitions from lcd, so it should not cause problems

**Comment by maruf0011** [comment]
Yup, that is correct. @etienne-napoleone

**Comment by hanjukim** [comment]
Let's forget about LCD.
